In [ ]:
#implementing linear regression with pytorch's in built tools

In [10]:
import torch.nn as nn
import torch
import numpy as np



In [9]:
inputs = np.array([[73,67,43],[91,88,65],[87,134,58],
                   [102,43,37],[69,96,70],[73,67,43],
                   [91,88,64],[87,134,58],[102,43,37],
                   [69,96,70],[73,67,43],[91,88,64],
                   [87,134,58],[102,43,37],[69,96,70]], dtype = "float32")

targets =np.array([[56,70],[81,101],[119,133],
                  [22,37],[103,119],[54,70],
                  [81,101],[119,113],[22,37],
                  [103,119],[56,70],[81,101],
                  [119,113],[22,37],[103,119]], dtype = "float32")
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [ ]:
#now we analysize the data in batches using TENSORDATASET which allows us to access rows from inputs and targets as tuples
#and provides standard apis for working with different types of dataset in pytorch


In [ ]:
from torch.utils.data import TensorDataset


In [11]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  65.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
#we will also create a DATALOADER which can split data into batches of predefined size while training. It also provide 
#utilities for data shuffling and samplinh
#it is used in a for in loop since it return multiple values

In [25]:
from torch.utils.data import DataLoader

In [27]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [28]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  65.],
        [ 73.,  67.,  43.]])
tensor([[ 54.,  70.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 81., 101.],
        [ 56.,  70.]])


In [ ]:
#instead of initializing the weghts and biases manually, we can define the model using the nn.linear class from pytorch

In [29]:
#define model, specifying the number of inputs and targets which are 3 and 2 respectively.
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[-0.4442, -0.1038,  0.4537],
        [ 0.4539,  0.4066,  0.0031]], requires_grad=True)
Parameter containing:
tensor([-0.5299,  0.2085], requires_grad=True)


In [30]:
#we then generate predictions with the model
preds = model(inputs)
preds

tensor([[-20.4001,  60.7157],
        [-20.5937,  77.4917],
        [-26.7661,  94.3564],
        [-33.5134,  64.1025],
        [ -9.3831,  70.7740],
        [-20.4001,  60.7157],
        [-21.0473,  77.4886],
        [-26.7661,  94.3564],
        [-33.5134,  64.1025],
        [ -9.3831,  70.7740],
        [-20.4001,  60.7157],
        [-21.0473,  77.4886],
        [-26.7661,  94.3564],
        [-33.5134,  64.1025],
        [ -9.3831,  70.7740]], grad_fn=<AddmmBackward0>)

In [ ]:
#our predictions are quite far from our targets if we compare both
#so we calculate the loss function

In [31]:
import torch.nn.functional as f

In [34]:
loss_fn = f.mse_loss
loss = loss_fn(preds,targets)
print(loss)

tensor(5750.7515, grad_fn=<MseLossBackward0>)


In [33]:
#we pass the model.parameter() so the method knows which matrix should be modified during update step
#you can also pass the learing rate
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
#we create a function to train the model

In [48]:
#repeat for given num of epochs
def fit(num_epochs,model,loss_fn, opt):
    for epoch in range(num_epochs):
        #train with batches of data
        for xb,yb in train_dl:
            preds = model(xb)
            loss = loss_fn(preds,yb)
            #compute gradient of loss
            loss.backward()
            #update predictions using gradients
            opt.step()
            #reset gradients to zero
            opt.zero_grad()
            #print the progress
    if(epoch+1) % 10 == 0:
            print('epoch[{}/{}],loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))
            
                  
    

In [55]:
fit(100,model,loss_fn,opt)

epoch[100/100],loss:17.0273


In [56]:
preds = model(inputs)
print(preds)

tensor([[ 56.9521,  68.2201],
        [ 82.8334, 101.2186],
        [118.5484, 121.0209],
        [ 20.8734,  38.0522],
        [101.8659, 118.6656],
        [ 56.9521,  68.2201],
        [ 82.1392, 100.0247],
        [118.5484, 121.0209],
        [ 20.8734,  38.0522],
        [101.8659, 118.6656],
        [ 56.9521,  68.2201],
        [ 82.1392, 100.0247],
        [118.5484, 121.0209],
        [ 20.8734,  38.0522],
        [101.8659, 118.6656]], grad_fn=<AddmmBackward0>)


In [57]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 54.,  70.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
#Our predictions are now quite close to our targets an we can use th model for any further excercise 

In [1]:
import jovian

<IPython.core.display.Javascript object>

In [2]:
jovian.commit(filename = 'Untitled5.ipynb')

<IPython.core.display.Javascript object>

[jovian] Committed successfully! https://jovian.com/danyal-hamza/untitled5


'https://jovian.com/danyal-hamza/untitled5'